# Generated by Django 4.2.1 on 2024-08-02 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('documento', models.CharField(max_length=20, verbose_name='CPF/CNPJ')),
                ('rua', models.CharField(max_length=250, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('loja', models.CharField(choices=[('BARBACOA', 'Barbacoa'), ('BARRA', 'Barra'), ('VILAS', 'Vilas'), ('SMART', 'Smart'), ('DIGITAL', 'Digital'), ('APP', 'App')], default='BARBACOA', max_length=10, verbose_name='Loja')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('documento', models.CharField(max_length=20, verbose_name='CPF/CNPJ')),
                ('rua', models.CharField(max_length=250, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('loja', models.CharField(choices=[('BARBACOA', 'Barbacoa'), ('BARRA', 'Barra'), ('VILAS', 'Vilas'), ('SMART', 'Smart'), ('DIGITAL', 'Digital'), ('APP', 'App')], default='BARBACOA', max_length=10, verbose_name='Loja')),
            ],
        ),
        migrations.CreateModel(
            name='Recebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data_emissao', models.DateField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('vencido', 'Vencido')], default='pendente', max_length=30)),
                ('loja', models.CharField(choices=[('BARBACOA', 'Barbacoa'), ('BARRA', 'Barra'), ('VILAS', 'Vilas'), ('SMART', 'Smart'), ('DIGITAL', 'Digital'), ('APP', 'App')], default='BARBACOA', max_length=10, verbose_name='Loja')),
                ('centro_custo', models.CharField(choices=[('Antecipação', 'Antecipação'), ('Bonificação', 'Bonificação'), ('Campanha', 'Campanha'), ('Comemoração', 'Comemoração'), ('Comissão', 'Comissão'), ('Diferido', 'Diferido'), ('Empréstimos', 'Empréstimos'), ('Equipamento', 'Equipamento'), ('Extra', 'Extra'), ('Folha de Pagamento', 'Folha de Pagamento'), ('Imposto', 'Imposto'), ('Investimentos', 'Investimentos'), ('Locação', 'Locação'), ('Manutenção', 'Manutenção'), ('Participação dos Lucros', 'Participação dos Lucros'), ('Sistema', 'Sistema'), ('Tarifa', 'Tarifa')], default='', max_length=50, verbose_name='Centro de Custo')),
                ('data_recebimento', models.DateField(blank=True, null=True, verbose_name='Data de Recebimento')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_dashboard.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data_emissao', models.DateField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('vencido', 'Vencido')], default='pendente', max_length=30)),
                ('loja', models.CharField(choices=[('BARBACOA', 'Barbacoa'), ('BARRA', 'Barra'), ('VILAS', 'Vilas'), ('SMART', 'Smart'), ('DIGITAL', 'Digital'), ('APP', 'App')], default='BARBACOA', max_length=10, verbose_name='Loja')),
                ('centro_custo', models.CharField(choices=[('Antecipação', 'Antecipação'), ('Bonificação', 'Bonificação'), ('Campanha', 'Campanha'), ('Comemoração', 'Comemoração'), ('Comissão', 'Comissão'), ('Diferido', 'Diferido'), ('Empréstimos', 'Empréstimos'), ('Equipamento', 'Equipamento'), ('Extra', 'Extra'), ('Folha de Pagamento', 'Folha de Pagamento'), ('Imposto', 'Imposto'), ('Investimentos', 'Investimentos'), ('Locação', 'Locação'), ('Manutenção', 'Manutenção'), ('Participação dos Lucros', 'Participação dos Lucros'), ('Sistema', 'Sistema'), ('Tarifa', 'Tarifa')], default='', max_length=50, verbose_name='Centro de Custo')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_dashboard.fornecedor')),
            ],
        ),
    ]
