# Generated by Django 4.2.1 on 2024-08-03 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_dashboard', '0002_loja_alter_pagamento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='nome',
            field=models.CharField(choices=[('BARBACOA', 'Barbacoa'), ('BARRA', 'Barra'), ('VILAS', 'Vilas'), ('SMART', 'Smart'), ('DIGITAL', 'Digital'), ('APP', 'App')], max_length=100),
        ),
        migrations.AlterField(
            model_name='usuarioperfil',
            name='lojas',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='app_dashboard.loja'),
        ),
        migrations.AlterField(
            model_name='usuarioperfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
