# Generated by Django 4.2.1 on 2024-08-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0006_alter_recebimento_status_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='loja',
            field=models.CharField(choices=[('BARBACOA', 'Barbacoa'), ('BARRA', 'Barra'), ('VILAS', 'Vilas'), ('SMART', 'Smart'), ('DIGITAL', 'Digital'), ('APP', 'App')], default='BARBACOA', max_length=10, verbose_name='Loja'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='loja',
            field=models.CharField(choices=[('BARBACOA', 'Barbacoa'), ('BARRA', 'Barra'), ('VILAS', 'Vilas'), ('SMART', 'Smart'), ('DIGITAL', 'Digital'), ('APP', 'App')], default='BARBACOA', max_length=10, verbose_name='Loja'),
        ),
    ]
