# Generated by Django 4.2.1 on 2024-08-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0007_cliente_loja_fornecedor_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='loja',
            field=models.CharField(choices=[('BARBACOA', 'Barbacoa'), ('BARRA', 'Barra'), ('VILAS', 'Vilas'), ('SMART', 'Smart'), ('DIGITAL', 'Digital'), ('APP', 'App')], default='BARBACOA', max_length=10, verbose_name='Loja'),
        ),
        migrations.AddField(
            model_name='recebimento',
            name='loja',
            field=models.CharField(choices=[('BARBACOA', 'Barbacoa'), ('BARRA', 'Barra'), ('VILAS', 'Vilas'), ('SMART', 'Smart'), ('DIGITAL', 'Digital'), ('APP', 'App')], default='BARBACOA', max_length=10, verbose_name='Loja'),
        ),
    ]
