# Generated by Django 4.2.1 on 2024-08-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0008_pagamento_loja_recebimento_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='centro_custo',
            field=models.CharField(choices=[('Locação', 'Locação'), ('Sistema', 'Sistema'), ('Folha de Pagamento', 'Folha de Pagamento'), ('Participação dos Lucros', 'Participação dos Lucros'), ('Tarifa', 'Tarifa'), ('Empréstimos', 'Empréstimos'), ('Investimentos', 'Investimentos'), ('Campanha', 'Campanha'), ('Comissão', 'Comissão'), ('Antecipação', 'Antecipação'), ('Imposto', 'Imposto'), ('Diferido', 'Diferido'), ('Extra', 'Extra'), ('Manutenção', 'Manutenção'), ('Comemoração', 'Comemoração'), ('Bonificação', 'Bonificação')], default='', max_length=50, verbose_name='Centro de Custo'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='centro_custo',
            field=models.CharField(choices=[('Locação', 'Locação'), ('Sistema', 'Sistema'), ('Folha de Pagamento', 'Folha de Pagamento'), ('Participação dos Lucros', 'Participação dos Lucros'), ('Tarifa', 'Tarifa'), ('Empréstimos', 'Empréstimos'), ('Investimentos', 'Investimentos'), ('Campanha', 'Campanha'), ('Comissão', 'Comissão'), ('Antecipação', 'Antecipação'), ('Imposto', 'Imposto'), ('Diferido', 'Diferido'), ('Extra', 'Extra'), ('Manutenção', 'Manutenção'), ('Comemoração', 'Comemoração'), ('Bonificação', 'Bonificação')], default='', max_length=50, verbose_name='Centro de Custo'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='centro_custo',
            field=models.CharField(choices=[('Locação', 'Locação'), ('Sistema', 'Sistema'), ('Folha de Pagamento', 'Folha de Pagamento'), ('Participação dos Lucros', 'Participação dos Lucros'), ('Tarifa', 'Tarifa'), ('Empréstimos', 'Empréstimos'), ('Investimentos', 'Investimentos'), ('Campanha', 'Campanha'), ('Comissão', 'Comissão'), ('Antecipação', 'Antecipação'), ('Imposto', 'Imposto'), ('Diferido', 'Diferido'), ('Extra', 'Extra'), ('Manutenção', 'Manutenção'), ('Comemoração', 'Comemoração'), ('Bonificação', 'Bonificação')], default='', max_length=50, verbose_name='Centro de Custo'),
        ),
        migrations.AddField(
            model_name='recebimento',
            name='centro_custo',
            field=models.CharField(choices=[('Locação', 'Locação'), ('Sistema', 'Sistema'), ('Folha de Pagamento', 'Folha de Pagamento'), ('Participação dos Lucros', 'Participação dos Lucros'), ('Tarifa', 'Tarifa'), ('Empréstimos', 'Empréstimos'), ('Investimentos', 'Investimentos'), ('Campanha', 'Campanha'), ('Comissão', 'Comissão'), ('Antecipação', 'Antecipação'), ('Imposto', 'Imposto'), ('Diferido', 'Diferido'), ('Extra', 'Extra'), ('Manutenção', 'Manutenção'), ('Comemoração', 'Comemoração'), ('Bonificação', 'Bonificação')], default='', max_length=50, verbose_name='Centro de Custo'),
        ),
    ]
