# Generated by Django 4.2.1 on 2024-08-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0010_pagamento_data_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='recebimento',
            name='data_recebimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Recebimento'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('vencido', 'Vencido')], default='pendente', max_length=30),
        ),
        migrations.AlterField(
            model_name='recebimento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('vencido', 'Vencido')], default='pendente', max_length=30),
        ),
    ]
