# Generated by Django 4.2.1 on 2024-08-02 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0011_recebimento_data_recebimento_alter_pagamento_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recebimento',
            name='fornecedor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_dashboard.fornecedor'),
        ),
    ]
