# Generated by Django 4.2.1 on 2024-08-02 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0013_alter_recebimento_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recebimento',
            name='fornecedor',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_dashboard.fornecedor'),
        ),
    ]
