# Generated by Django 4.2.1 on 2024-08-02 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0017_alter_recebimento_fornecedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recebimento',
            name='fornecedor',
        ),
    ]
